import assert from "node:assert/strict";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { describe, test } from "node:test";
import { fileURLToPath } from "node:url";
import {
  enginesDir,
  parseEngineConsts,
  parseSelectCardIds,
  pkgRoot,
  uniqueYdkIds,
} from "./lib/parse.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const catalog = JSON.parse(
  readFileSync(join(here, "effects/toon-2026.json"), "utf8"),
);
const PLAYER_ACTIVATED = new Set(["activate", "ignition", "quick", "trigger"]);

const LOCATION = {
  botDeck: [0x01, 0],
  botHand: [0x02, 0],
  botMonster: [0x04, 0],
  botSpell: [0x08, 0],
  botGrave: [0x10, 0],
  botExtra: [0x40, 0],
  oppHand: [0x02, 1],
  oppMonster: [0x04, 1],
  oppSpell: [0x08, 1],
  oppGrave: [0x10, 1],
};

function locSeq(key, index) {
  if (key === "botSpell" || key === "oppSpell") {
    return index === 0 ? 5 : Math.min(index - 1, 4);
  }
  return Math.min(index, 6);
}

function puzzleLua(entry, index) {
  const lines = [
    `-- Generated Toon 2026 effect case ${index}: ${entry.name}`,
    `-- ${entry.effect}`,
    `-- expect: ${entry.expect?.note ?? ""}`,
    "Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI,5)",
    "Debug.SetPlayerInfo(0,8000,0,0)",
    "Debug.SetPlayerInfo(1,8000,0,0)",
  ];
  const setup = entry.setup || {};
  for (const [key, pair] of Object.entries(LOCATION)) {
    const ids = setup[key] || [];
    const [loc, owner] = pair;
    ids.forEach((id, i) => {
      const seq = locSeq(key, i);
      const pos = loc === 0x04 ? 0x1 : loc === 0x08 && seq === 5 ? 0x5 : 0x1;
      lines.push(
        `Debug.AddCard(${id},${owner},${owner},${loc},${seq},${pos}) -- ${key}`,
      );
    });
  }
  lines.push("Debug.ReloadFieldEnd()");
  lines.push(
    `Debug.ShowHint("${entry.name}: ${String(entry.effect).replace(/"/g, "'")}")`,
  );
  return `${lines.join("\n")}\n`;
}

describe("Toon 2026 effect catalog", () => {
  const ydkIds = uniqueYdkIds(join(pkgRoot, "ydk", catalog.ydkFileName));
  const catalogIds = new Set(catalog.effects.map((e) => e.cardId));
  const engineText = readFileSync(join(pkgRoot, catalog.engineFile), "utf8");
  const consts = parseEngineConsts(enginesDir());
  const selectIds = parseSelectCardIds(engineText, consts);

  test("every YDK unique id has at least one catalog entry", () => {
    const missing = [...ydkIds].filter((id) => !catalogIds.has(id));
    assert.deepEqual(missing, [], `Missing catalog cards: ${missing.join(", ")}`);
  });

  test("catalog cardIds are in the YDK", () => {
    const extra = [...catalogIds].filter((id) => !ydkIds.has(id));
    assert.deepEqual(extra, [], `Catalog ids not in YDK: ${extra.join(", ")}`);
  });

  test("every player-activated effect has setup and action", () => {
    const bad = catalog.effects.filter((e) => {
      if (!PLAYER_ACTIVATED.has(e.kind)) return false;
      return !e.setup || !e.action || !e.effect;
    });
    assert.equal(bad.length, 0, JSON.stringify(bad.map((e) => e.name)));
  });

  test("selectCardContains ids appear in ToonEngine SelectCard calls", () => {
    const missing = [];
    for (const e of catalog.effects) {
      const want = e.expect?.selectCardContains || [];
      for (const id of want) {
        if (!selectIds.has(id)) missing.push(`${e.name}:${id}`);
      }
    }
    assert.deepEqual(missing, [], `SelectCard gaps: ${missing.join(", ")}`);
  });

  test("generate EDOPro Debug puzzles", () => {
    const outDir = join(here, "puzzles");
    mkdirSync(outDir, { recursive: true });
    let written = 0;
    catalog.effects.forEach((entry, i) => {
      const slug = String(entry.name)
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "");
      const file = join(
        outDir,
        `${catalog.deckId}-${entry.cardId}-${i}-${slug}.lua`,
      );
      writeFileSync(file, puzzleLua(entry, i));
      written += 1;
    });
    writeFileSync(
      join(outDir, ".gitkeep"),
      "# generated by tests/effects.test.mjs\n",
    );
    assert.ok(written >= catalog.effects.length);
  });
});
